Bivariate analys
neurospin/pymultifracs pull request #13
Opened 2021-02-15 16:03 UTC by MerlinDumeur

2021-02-22 18:09 UTC, philouc requested changes

2021-02-22 18:09 UTC, philouc commented on pymultifracs/bivariate/bivariate_structurefunction.py
> +        self.nrep = 1
What is nrep here? This should be clarified. I'm guessing you refer to the number of repetitions, i.e. the number of pairs of signals on which you aim to compute the bivariate MF spectrum?

2021-02-22 18:09 UTC, philouc commented on pymultifracs/cumulants.py
> +        TODO Debug this function
Don't leave this kind of comment

2021-03-01 10:11 UTC, MerlinDumeur commented on pymultifracs/bivariate/bivariate_structurefunction.py
> +        self.nrep = 1
This is correct, nrep is indeed the number of repetitions. I defined it for all multiresolution quantities (from which bivariate structure functions inherit), because it is used in the univariate case, to perform the multifractal analysis on multiple signals at once. I did not yet try to implement the same possibility with bivariate MF analysis, so in the meantime I have to force nrep = 1.

2021-03-01 10:15 UTC, MerlinDumeur commented on pymultifracs/cumulants.py
> +        TODO Debug this function
This function most likely does not work now because of the changes I've made, but since I've never had to use it, I'm not certain it would be worth spending time fixing. What do you recommend ?

2021-03-01 10:27 UTC, philouc commented on pymultifracs/cumulants.py
> +        TODO Debug this function
You should probably remove it for the ease of maintenance.

2021-03-01 11:52 UTC, philouc commented
LGTM

2021-03-01 11:52 UTC, merged